### ISSUE TITLE
Error 'SpaceUVEditor' object has no attribute 'pixel_snap_mode' for blender 3.6 and 4.0

### ISSUE THREAD

**Issue by acgc99** [TheStrokeForge/Vox-Cleaner-V2#4]
The addon gives an error on blender 3.6 and 4.0. It works on 3.3.

```
OBJ import of 'vox.obj' took 7.9 ms
Info: Removed 5301 vertice(s)
True
Info: Applied modifier: MrCleaner
Traceback (most recent call last):
  File "C:\Users\acgc9\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VoxCleaner_V2_Free.py", line 713, in execute
    VoxMethods.UVScaling(context)
  File "C:\Users\acgc9\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VoxCleaner_V2_Free.py", line 450, in UVScaling
    space.uv_editor.pixel_snap_mode = 'CORNER'
AttributeError: 'SpaceUVEditor' object has no attribute 'pixel_snap_mode'
Error: Python: Traceback (most recent call last):
  File "C:\Users\acgc9\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VoxCleaner_V2_Free.py", line 713, in execute
    VoxMethods.UVScaling(context)
  File "C:\Users\acgc9\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VoxCleaner_V2_Free.py", line 450, in UVScaling
    space.uv_editor.pixel_snap_mode = 'CORNER'
AttributeError: 'SpaceUVEditor' object has no attribute 'pixel_snap_mode'
```

blender 3.6:
![Screenshot (467)](https://github.com/TheStrokeForge/Vox-Cleaner-V2/assets/96864661/18535207-8ea3-45db-8610-d8a877ecf56e)

blender 4.0:
![Screenshot (468)](https://github.com/TheStrokeForge/Vox-Cleaner-V2/assets/96864661/ec6ba7d9-c841-4275-876f-b7d3c5675482)

**Comment by acgc99** [comment]
Change to `space.uv_editor.pixel_round_mode = 'CORNER'`.

Related to https://github.com/TheStrokeForge/Vox-Cleaner-V2/issues/1

**Comment by TheStrokeForge** [comment]
Hey,

no need to worry! I've uploaded a new version of the add-on, you can just
use that. It's got the error solved.

Let me know if that helps
Cheers
Farhan

**Comment by acgc99** [comment]
Thanks for your attention. I don't see any update on this repo code.

**Comment by TheStrokeForge** [comment]
Just updated the repo. Thanks for the ping! This version currently doesn't
work on the Blender version 4.0, however I'm working on Vox Cleaner 3. It
will have a lot more features, and will support Blender 4.0

Cheers!
Farhan

**Comment by acgc99** [comment]
Many thanks!
